#!/usr/bin/env bash
# Adapter: Codex CLI (~/.codex)
# Native skills. Native sub-agents, but declared as TOML rather than markdown.
#
# HARNESS_* are the adapter contract: install.sh sources this file and reads them.
# shellcheck disable=SC2034

HARNESS_NAME="Codex CLI"
HARNESS_CAPS="subagents slash-commands"

# Codex skills carry no model pin and no invocation flag.
HARNESS_DROP_KEYS="harness model disable-model-invocation"

harness_detect() {
  command -v codex >/dev/null 2>&1 || [ -d "$HOME/.codex" ]
}

harness_root()       { printf '%s' "$HOME/.codex"; }
harness_skills_dir() { printf '%s' "$HOME/.codex/skills"; }
harness_skill_dest() { printf '%s' "$HOME/.codex/skills/$1"; }

# Map canonical model tiers onto Codex's. Verified 2026-08-10 against the model
# catalog the installed CLI itself fetches, ~/.codex/models_cache.json: Sol is the
# frontier tier, Terra the balanced tier, Luna the fast tier. Re-check that file
# when Codex ships a new generation; the previous map pointed at gpt-5.4, which is
# now two tiers down.
codex_model_for() {
  case "$1" in
    opus)   printf 'gpt-5.6-sol' ;;
    sonnet) printf 'gpt-5.6-terra' ;;
    haiku)  printf 'gpt-5.6-luna' ;;
    *)      printf '%s' "$1" ;;
  esac
}

# Sub-agents become TOML with the body under developer_instructions.
harness_agent_install() {
  local src="$1" name dest desc model tools
  name="$(basename "$src" .md)"
  dest="$HOME/.codex/agents/$name.toml"

  if [ -e "$dest" ] && ! $FORCE; then
    info "skip  agents/$name.toml (exists, use --force)"
    return 0
  fi

  desc="$(frontmatter_field "$src" description)"
  model="$(codex_model_for "$(frontmatter_field "$src" model)")"
  tools="$(frontmatter_field "$src" tools)"

  # Codex has no per-agent tool allowlist. Say so rather than dropping silently.
  if [ -n "$tools" ]; then
    warn "$name: dropping tool restriction '$tools' (Codex has no equivalent)"
  fi

  {
    printf '# Generated by dotagents from agents/%s.md. Edits here are overwritten.\n' "$name"
    printf 'name = "%s"\n' "$name"
    printf 'description = "%s"\n' "$(printf '%s' "$desc" | sed 's/\\/\\\\/g; s/"/\\"/g')"
    [ -n "$model" ] && printf 'model = "%s"\n' "$model"
    printf 'developer_instructions = %s\n' "'''"
    # Body only: strip the frontmatter block entirely.
    awk 'NR==1 && $0=="---" { infm=1; next } infm && $0=="---" { infm=0; next } !infm' "$src"
    printf "%s\n" "'''"
  } | do_write "$dest"

  info "agent $name.toml"
}

harness_instructions_dest() { printf '%s' "$HOME/.codex/AGENTS.md"; }
